### ISSUE TITLE
theme: convert Exo font from ttf to woff2

### ISSUE THREAD

**Issue by davidsneighbour** [davidsneighbour/kollitsch.dev#133]
use https://pypi.org/project/fonttools/

> Font files will often be provided in the TrueType format (ttf), but for the web it’s a much better idea to compress the font file to the WOFF2 format, to save on space. You can use a tool like [FontTools](https://pypi.org/project/FontTools/) to compress a font file as WOFF2. More user-friendly GUI or online tools will surely become available really soon.

**Comment by davidsneighbour** [comment]
Won't be doing that too soon. The variable font can't be transformed and having the variable font is more important than something we can solve via hugo-pwa caching.

**Comment by brycewray** [comment]
@davidsneighbour I had wondered why you were using a TTF, so I found this issue. Not sure why you weren’t able to transform the Exo variable font, but I have done so and am putting the files on my repo for your consideration. If they don’t serve your purposes, please feel free to ignore this. Let me know when I can delete them from my repo.

**Exo variable, regular**:
https://github.com/brycewray/hugo-site/blob/main/static/fonts/Exo-regular-variable-not-subset.woff2

**Exo variable, italic**:
https://github.com/brycewray/hugo-site/blob/main/static/fonts/Exo-italic-variable-not-subset.woff2

...and, in case you’re interested, also the Exo2 variations thereof...

**Exo2 variable, regular**:
https://github.com/brycewray/hugo-site/blob/main/static/fonts/Exo2-regular-variable-not-subset.woff2

**Exo2 variable, italic**:
https://github.com/brycewray/hugo-site/blob/main/static/fonts/Exo2-italic-variable-not-subset.woff2

**Comment by davidsneighbour** [comment]
Let me play around with this...

**Comment by davidsneighbour** [comment]
It works, of course :) May I ask how you converted the font? Or did they release it in woff2 now, and I am just behind on this?

**Comment by brycewray** [comment]
> It works, of course :) May I ask how you converted the font? Or did they release it in woff2 now, and I am just behind on this?

I used [pyftsubset](https://fonttools.readthedocs.io/en/latest/subset/), with the `unicodes` parameter set to `'*'`. I downloaded the original TTFs from Google Fonts.

**Comment by davidsneighbour** [comment]
Great :) when I tried that on a variable font some time back it failed and I didn't go deeper. I did use Glyphhanger though, so it might be tool-related. It worked wonders on the fonts in my german language blog years back... cut out all the extra characters, but not the beloved ümlauts ;)

closing this again. thank you for your help!

https://github.com/zachleat/glyphhanger

**Comment by brycewray** [comment]
Glad I could help. Will delete those files from my repo, now.
