### ISSUE TITLE
Encountering 'Not Found' Error When Running 'hugo-debug' Package

### ISSUE THREAD

**Issue by andgar2010** [davidsneighbour/kollitsch.dev#329]
Reference: https://github.com/davidsneighbour/hugo-blockify/issues/129

**Comment by davidsneighbour** [comment]
Let's discuss this over at https://github.com/davidsneighbour/hugo-blockify/issues/129. This issue collection is more or less for my own website, and the `hugo-debug` package is part of hugo-blockify. I answered over there.
