### ISSUE TITLE
Black-on-black in code block “tabs”

### ISSUE THREAD

**Issue by brycewray** [davidsneighbour/kollitsch.dev#774]
Viewing in macOS 14.3.1 on Google Chrome, with light mode in use, I see an active code block “tab” (*e.g.*, on your post at https://kollitsch.dev/blog/2024/refactoring-gohugo-aliases/) as essentially black-on-black and, thus, unreadable. Screen shot:

<img width="956" alt="Screenshot 2024-02-26 at 9 43 05 AM" src="https://github.com/davidsneighbour/kollitsch.dev/assets/14099446/438a3dd8-aa33-4b50-9bc2-90476c167915">

In dark mode, OTOH, it’s fine, with white text on black background:

<img width="1320" alt="Screenshot 2024-02-26 at 9 46 52 AM" src="https://github.com/davidsneighbour/kollitsch.dev/assets/14099446/74b1f12f-3de4-4d18-9830-0452844f8998">

**Comment by davidsneighbour** [comment]
That's because my light mode is basically ignored by me ;) I'll check what is going on here ;)

**Comment by davidsneighbour** [comment]
hmm... the nav looks weird too now ;) it's like fixing one thing and breaking two others :D
